### ISSUE TITLE
Globales DARIAH Menü mit Javascript und JSON laden

### ISSUE THREAD

**Issue by jbiermann** [DARIAH-DE/StyleGuideTemplate#10]
wie im alten Styleguide.

#7

**Comment by maltevogl** [comment]
Dafür müssen wir die Struktur in https://github.com/DARIAH-DE/StyleGuideTemplate/blob/acbac3ffe48a5ce38368779a5d72d902b61b0973/templates/index.html#L179
automatisch mit dem JSON in https://res.de.dariah.eu/globalmenu/menu.json füllen. Sollte gehen...

Ein erster Versuch [hier](https://jsfiddle.net/9uhc3/1783/)

**Comment by maltevogl** [comment]
Closed by #21
