### ISSUE TITLE
Styleguide auch ohne Menü oben

### ISSUE THREAD

**Issue by jbiermann** [DARIAH-DE/StyleGuideTemplate#12]
ähnlich wie bei den Mockups

#7

**Comment by maltevogl** [comment]
Meinst du ein neues Template anlegen? Um zu zeigen wie es geht kann man auch in html-elements schauen `<body class="site -no-header">`,z.b. [hier](https://github.com/DARIAH-DE/StyleGuideTemplate/blob/acbac3ffe48a5ce38368779a5d72d902b61b0973/templates/html-elements.html#L14)

**Comment by jbiermann** [comment]
ja wenn das nur eine CSS Klasse ist, nicht, dann einfach in die Doku aufnehmen. Sowas wie _ohne Menü oben einfach mit blauen Balken Bitte XYZ aus dem HTML entfernen und folgende Klasse zuweisen._

**Comment by maltevogl** [comment]
Das verstecken des headers ist als Beispiel in index.html erwähnt.
