### ISSUE TITLE
Mittlerer Bereich von der Breite anpassbar machen

### ISSUE THREAD

**Issue by jbiermann** [DARIAH-DE/StyleGuideTemplate#13]
und das Logo in der Mitte optional machen, das wird nicht für alle Tools benötigt. 

#7

**Comment by maltevogl** [comment]
Das template für ein Tool Beispiel enthält ein geändertes Logo, die Design-Entscheidung bezüglich der Breite (breakpoints etc) sind im design-primer.de.md erklärt. Alle Elemente können durch hinzufügen von class = "hidden" versteckt werden.
