### ISSUE TITLE
Sebstdokumentierender Styleguide

### ISSUE THREAD

**Issue by jbiermann** [DARIAH-DE/StyleGuideTemplate#15]
#7 

Auflisten, welche Frameworks benutzt werden. Außerdem sollten Beispiele darin enthalten sein, wie die Textformatierungen und Überschriften aussehen sollen. Beispiele für verschiedene Kontrollelemente wie Buttons, Fehler- Info und OK Meldungen und ggf. Dialoge sollten auch Teil des Styleguides sein. Das macht es den Entwicklern erheblich einfacher das Tool an den Styleguide anzupassen.

**Comment by maltevogl** [comment]
Die index.html Seite im templates Ordner erklärt jetzt ausführlich, wo die Beispiele zu finden sind und listet die Abhängigkeiten.
