### ISSUE TITLE
Footer dynamisch / mehsprachig

### ISSUE THREAD

**Issue by jbiermann** [DARIAH-DE/StyleGuideTemplate#16]
#7 

Hier sollte es auch mindestens eine englische Version davon geben. Vielleicht kann man die Links auch per Javascript laden? Dann wäre das auch leicht zentral anpassbar.  Der Text „Alle Inhalte dieser Seite unterliegen der CC-BY-4.0-Lizenz, sofern nicht anders gekennzeichnet.“ ist eventuell nicht für die Tools passend.

**Comment by maltevogl** [comment]
Ich denke der Footer könnte je nach Tool doch unterschiedlich sein. Daher würde ich dort nichts dynamisch laden. Die beiden Version der frontpage templates enthalten jetzt deutsche und englische Footer. Der Hinweis auf die Anpassung der Lizenz steht in der index.html Datei.
