### ISSUE TITLE
Bootstrap Kompatibilität

### ISSUE THREAD

**Issue by maltevogl** [DARIAH-DE/StyleGuideTemplate#20]
Einige Tools nutzen Bootstrap. Kann das weiterhin mit CSS / JS eingebunden werden ohne Konflikte mit dem Design?

**Comment by maltevogl** [comment]
Closed in favor of #18

**Comment by bschnabel** [comment]
see https://github.com/DARIAH-DE/StyleGuideTemplate/issues/18#issuecomment-468343972
