### ISSUE TITLE
Lizenzangabe fehlt

### ISSUE THREAD

**Issue by schildwaechter** [DARIAH-DE/StyleGuideTemplate#4]
https://wiki.de.dariah.eu/pages/viewpage.action?pageId=38080370#Empfehlungenf%C3%BCrForschungsdaten,ToolsundMetadateninderDARIAH-DEInfrastruktur-Lizenzenf%C3%BCrCode

**Comment by maltevogl** [comment]
Die Version 2 hat GNU AFFERO das sollten wir eventuell anpassen.

**Comment by maltevogl** [comment]
Closed, License ist dabei.
