### ISSUE TITLE
Einiges zum Bootstrap 3 Template

### ISSUE THREAD

**Issue by mrbeak** [DARIAH-DE/StyleGuideTemplate#5]
1. Bei der Arbeit von Mateo ist das Menü nicht responsive. Zieht man
   das Fenster kleiner verschwindet die rechte Menüleiste. In seinem Fall
   ist das nicht weiter tragisch, da alle Menüpunkte nachwievor über das
   horizontale Menü im Header zugänglich sind, was auch responsive ist.
   Wenn es viele Menüpunkte gibt, so wie bei uns im dariah admin portal,
   glauben wir, dass es nichmehr gut aussehen würde alle Menüpunkte in
   den Header zu nehmen. Das vertikale Menü auf der linken Seite müsste
   also skalierbar werden und in irgendeiner Form auch auf kleineren
   Bildschirmen dargestellt werden.
2. Die Bootstrap 3 Portieren von Mateo scheint uns noch nicht komplett
   ausgereift zu sein. Im header stimmen einige Abstände noch nicht, der
   Link StyleGuie Template wird beim hovern mit weißen Hintergrund
   versehen... Auch der Hauptbereich ist jeh nach Fensterbreite nicht
   ganz zentriert sondern eher etwas nach links verschoben.

Das Ziel sollte wie bereits von Klaus angesprochen sein, die Templates von Mateo (https://github.com/DARIAH-DE/StyleGuideTemplate/tree/b3) und Tobias (https://colreg.de.dariah.eu/colreg3/collections/) zusammenzuführen.

Beste Grüße

**Comment by maltevogl** [comment]
Das neue Design benutzt kein Bootstrap mehr. Ich schließe das Issue daher mal. Sollte das Problem mit dem neuen Design bestehen, bitte wieder öffnen.
